{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: git@github.com:{{ $.Values.sourceRepo }}.git
      targetRevision: HEAD
      ref: reporoot

    - chart: {{ .chart.name }}
      repoURL: {{ .chart.url }}
      targetRevision: {{ .chart.version }}

      helm:
        valueFiles:
          - $reporoot/values/{{ .name }}.yaml
          {{- if .secrets.enabled }}
          - secrets://https://raw.githubusercontent.com/{{ $.Values.sourceRepo }}/main/secrets/{{ .name }}.yaml
          {{- end }}

		{{- if .homepage.enabled }}
        valuesObject:
          ingress:
            enabled: true
            ingressClassName: nginx

            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              cert-manager.io/cluster-issuer: "selfsign-clusterissuer"

              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: {{ default (.name | title) .homepage.name | quote}}
              gethomepage.dev/description: {{ default "" .homepage.description | quote }}
              gethomepage.dev/group: {{ default (.namespace | title) }}
              gethomepage.dev/icon: {{ default (print .name ".png" ) .homepage.icon }}

            hosts:
              - {{ .name }}.jesber.duckdns.org
            tls:
              - hosts:
                - {{ .name }}.jesber.duckdns.org
		{{- end }}


  destination:
     server: https://kubernetes.default.svc
     namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
---
{{ end }}
