apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default

  sources:
    - chart: authentik
      repoURL: https://charts.goauthentik.io/
      targetRevision: 2024.8.2

      helm:
        values: |
          - $values/values/authentik.yaml
    - repoURL: git@github.com:arch-err/Cluster-POC.git
      targetRevision: master
      ref: values

  destination:
     server: https://kubernetes.default.svc
     namespace: authentication
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest

    syncOptions:
      - CreateNamespace=true
