apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.5.1

      helm:
        valueFiles:
          - $reporoot/values/grafana.yaml
          - $reporoot/secrets/grafana.yaml

    - repoURL: git@github.com:arch-err/Cluster-POC.git
      targetRevision: HEAD
      ref: reporoot

  destination:
     server: https://kubernetes.default.svc
     namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
