apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
spec:
  project: default

  sources:
    - chart: influxdb2
      repoURL: https://helm.influxdata.com/
      targetRevision: 2.1.2

      helm:
        valueFiles:
          - $reporoot/values/influxdb.yaml
          - secrets://https://raw.githubusercontent.com/arch-err/Cluster-POC/main/secrets/influxdb.yaml

    - repoURL: git@github.com:arch-err/Cluster-POC.git
      targetRevision: HEAD
      ref: reporoot

  destination:
     server: https://kubernetes.default.svc
     namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
