# Default values for apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


sourceRepo: arch-err/Cluster-POC

sourceRepoUrl:
sourceRepoRevision: HEAD

apps:
  - name: grafana
    namespace: monitoring
    chart:
      url: https://grafana.github.io/helm-charts
      name: grafana
      version: 8.5.1
    homepage:
      enabled: true
      description: "Platform for data analytics and monitoring"
    secrets:
      enabled: true
  - name: influxdb
    namespace: monitoring
    chart:
      url: https://helm.influxdata.com/
      name: influxdb2
      version: 2.1.2
    secrets:
      enabled: true
    homepage:
      enabled: true
  - name: prometheus
    namespace: monitoring
    chart:
      url: https://prometheus-community.github.io/helm-charts
      name: prometheus
      version: 25.27.0
    secrets:
      enabled: false
    homepage:
      enabled: false
  - name: homepage
    namespace: homepage
    chart:
      url: https://jameswynn.github.io/helm-charts
      name: homepage
      version: 2.0.1
    secrets:
      enabled: false
    homepage:
      enabled: false
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   homepage:
  #     enabled: true
