# Default values for apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


sourceRepo: arch-err/Cluster-POC

sourceRepoUrl:
sourceRepoRevision: HEAD

apps:
  - name: grafana
    namespace: monitoring
    chart:
      url: https://grafana.github.io/helm-charts
      name: grafana
      version: 8.5.1
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        enabled: true
        description: "Platform for data analytics and monitoring"
  - name: influxdb
    namespace: monitoring
    chart:
      url: https://helm.influxdata.com/
      name: influxdb2
      version: 2.1.2
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        enabled: true
  - name: prometheus
    namespace: monitoring
    privileged: true
    chart:
      url: https://prometheus-community.github.io/helm-charts
      name: prometheus
      version: 25.27.0
    secrets:
      enabled: false
    ingress:
      valuesSection: server
      enabled: true
      homepage:
        enabled: true
  - name: homepage
    namespace: homepage
    chart:
      url: https://jameswynn.github.io/helm-charts
      name: homepage
      version: 2.0.1
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: false
  - name: portainer
    namespace: portainer
    chart:
      url: https://portainer.github.io/k8s/
      name: portainer
      version: 1.0.53
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: true
        group: "Cluster Management"
  # - name: harbor
  #   namespace: harbor
  #   chart:
  #     url: https://helm.goharbor.io
  #     name: harbor
  #     version: 1.15.1
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: false
  #     homepage:
  #       enabled: false
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
