# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argocd-ingress
#   namespace: argocd
#   annotations:
#     # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#     # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     cert-manager.io/cluster-issuer: "selfsign-clusterissuer"
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: argo.jesber.duckdns.org
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: argocd-server
#             port:
#               name: http
#   tls:
#   - hosts:
#     - argo.jesber.duckdns.org
#     secretName: argocd-server-tls # as expected by argocd-server
