apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default

  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.14.5

    helm:
      values: |
        installCRDs: true
        # extraArgs:
        #   - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53


  destination:
     server: https://kubernetes.default.svc
     namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
