apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default

  source:
    chart: traefik/traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 30.1.0

    # helm:
    #   values: |
    #     controller:
    #       hostNetwork: true
    #       hostPort:
    #         enabled: true
    #       kind: DaemonSet
    #       service:
    #         enabled: false
    #       extraArgs:
    #         enable-ssl-passthrough: true

  destination:
     server: https://kubernetes.default.svc
     namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # managedNamespaceMetadata:
    #   labels:
    #     pod-security.kubernetes.io/enforce: privileged
    #     pod-security.kubernetes.io/enforce-version: latest

    syncOptions:
      - CreateNamespace=true
